#if !defined(AFX_COLUMNHEADERS_H__E1295301_366F_48D7_A3BC_F6B765F76981__INCLUDED_)
#define AFX_COLUMNHEADERS_H__E1295301_366F_48D7_A3BC_F6B765F76981__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CColumnHeader;

/////////////////////////////////////////////////////////////////////////////
// CColumnHeaders wrapper class

class CColumnHeaders : public COleDispatchDriver
{
public:
	CColumnHeaders() {}		// Calls COleDispatchDriver default constructor
	CColumnHeaders(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CColumnHeaders(const CColumnHeaders& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetCount();
	void SetCount(long nNewValue);
	CColumnHeader Add(VARIANT* Index, VARIANT* Key, VARIANT* Text, VARIANT* Width, VARIANT* Alignment);
	void Clear();
	CColumnHeader GetItem(VARIANT* Index);
	void Remove(VARIANT* Index);
	LPUNKNOWN _NewEnum();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_COLUMNHEADERS_H__E1295301_366F_48D7_A3BC_F6B765F76981__INCLUDED_)
